### ISSUE TITLE
Results not accurate.

### ISSUE THREAD

**Issue by h4ck1th4rd** [skygxsky/Tiktokshop_signature#1]
Hi,

its print out: 

JZbQSQAARfhQ6dTxn468JyWW0F 25 length hash.

While the original hash is: 47 length example: "_02B4Z6wo00101yRyOHwAJXy6pQAARSK34au-5AwmAyV8ur"

Wont work for commenting.

**Comment by skygxsky** [comment]
Different websites have different signature for certain parameters. Which website parameters did you crack?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "skygxsky/Tiktokshop_signature"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 中午11:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[skygxsky/Tiktokshop_signature] Results not accurate. (#1)





 
Hi,
 
its print out:
 
JZbQSQAARfhQ6dTxn468JyWW0F 25 length hash.
 
While the original hash is: 47 length example: "_02B4Z6wo00101yRyOHwAJXy6pQAARSK34au-5AwmAyV8ur"
 
Wont work for commenting.

**Comment by h4ck1th4rd** [comment]
Link: https://www.tiktok.com/api/comment/publish/?aid=1988&app_name=tiktok_web&device_platform=web&referer=&root_referer=https:%2F%2Fwww.tiktok.com%2F&user_agent=Mozilla%2F5.0+(Linux%3B+Android+6.0%3B+Nexus+5+Build%2FMRA58N)+AppleWebKit%2F537.36+(KHTML,+like+Gecko)+Chrome%2F88.0.4324.146+Mobile+Safari%2F537.36&cookie_enabled=true&screen_width=803&screen_height=724&browser_language=en-US&browser_platform=MacIntel&browser_name=Mozilla&browser_version=5.0+(Linux%3B+Android+6.0%3B+Nexus+5+Build%2FMRA58N)+AppleWebKit%2F537.36+(KHTML,+like+Gecko)+Chrome%2F88.0.4324.146+Mobile+Safari%2F537.36&browser_online=true&ac=3g&timezone_name=Asia%2FKuwait&page_referer=https:%2F%2Fwww.tiktok.com%2F%40amydcoughlin%3F&priority_region=&verifyFp=verify_kl98yr4f_gJaTgYJl_h14T_4XOZ_9M8A_cZRKmL5iyvon&appId=1233&region=KW&appType=m&isAndroid=false&isMobile=false&isIOS=false&OS=mac&did=6906866569952691714&aweme_id=6945339337219296513&text=ddos+it2&device_id=6906866569952691714&

**Comment by skygxsky** [comment]
抖音app我没研究过，感觉应该很难，我这个是web抖店商家后台的参数


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "skygxsky/Tiktokshop_signature"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [skygxsky/Tiktokshop_signature] Results not accurate. (#1)





 
Link: https://www.tiktok.com/api/comment/publish/?aid=1988&amp;app_name=tiktok_web&amp;device_platform=web&amp;referer=&amp;root_referer=https:%2F%2Fwww.tiktok.com%2F&amp;user_agent=Mozilla%2F5.0+(Linux%3B+Android+6.0%3B+Nexus+5+Build%2FMRA58N)+AppleWebKit%2F537.36+(KHTML,+like+Gecko)+Chrome%2F88.0.4324.146+Mobile+Safari%2F537.36&amp;cookie_enabled=true&amp;screen_width=803&amp;screen_height=724&amp;browser_language=en-US&amp;browser_platform=MacIntel&amp;browser_name=Mozilla&amp;browser_version=5.0+(Linux%3B+Android+6.0%3B+Nexus+5+Build%2FMRA58N)+AppleWebKit%2F537.36+(KHTML,+like+Gecko)+Chrome%2F88.0.4324.146+Mobile+Safari%2F537.36&amp;browser_online=true&amp;ac=3g&amp;timezone_name=Asia%2FKuwait&amp;page_referer=https:%2F%2Fwww.tiktok.com%2F%40amydcoughlin%3F&amp;priority_region=&amp;verifyFp=verify_kl98yr4f_gJaTgYJl_h14T_4XOZ_9M8A_cZRKmL5iyvon&amp;appId=1233&amp;region=KW&amp;appType=m&amp;isAndroid=false&amp;isMobile=false&amp;isIOS=false&amp;OS=mac&amp;did=6906866569952691714&amp;aweme_id=6945339337219296513&amp;text=ddos+it2&amp;device_id=6906866569952691714&amp;

**Comment by h4ck1th4rd** [comment]
OK Thank you.
